Name:           ros-melodic-open-manipulator-with-tb3
Version:        1.1.0
Release:        2%{?dist}
Summary:        ROS open_manipulator_with_tb3 package

Group:          Development/Libraries
License:        Apache 2.0
URL:            http://wiki.ros.org/open_manipulator_with_tb3
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-melodic-open-manipulator-with-tb3-description
Requires:       ros-melodic-open-manipulator-with-tb3-tools
Requires:       ros-melodic-open-manipulator-with-tb3-waffle-moveit
Requires:       ros-melodic-open-manipulator-with-tb3-waffle-pi-moveit
BuildRequires:  ros-melodic-catkin

%description
ROS-enabled OpenManipulator is a full open robot platform consisting of
OpenSoftware​, OpenHardware and OpenCR(Embedded board)​. The OpenManipulator is
allowed users to control it more easily by linking with the MoveIt! package.
Moreover it has full hardware compatibility with TurtleBot3​. Even if you do not
have a real robot, you can control the robot in the Gazebo simulator​.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Tue Feb 12 2019 Pyo <pyo@robotis.com> - 1.1.0-2
- Autogenerated by Bloom

* Tue Feb 12 2019 Pyo <pyo@robotis.com> - 1.1.0-1
- Autogenerated by Bloom

* Tue Feb 12 2019 Pyo <pyo@robotis.com> - 1.1.0-0
- Autogenerated by Bloom

